        PLEASE NOTE: AN EXAMPLE OF CONVERTING A STATEMENT TO SOMETHING ELSE

(1)     DO CONVERT ABSTAIN FROM LABEL TO COME FROM LABEL
        DO READ OUT #1
        DO ABSTAIN FROM (1)
        DO READ OUT #2
        DO GIVE UP

        PLEASE NOTE: THE ABSTAIN FROM WILL RUN LIKE A COME FROM, SO THE FIRST
        READ OUT WILL BE SKIPPED AND THE PROGRAM PRODUCES JUST "II"

