        PLEASE NOTE: AN EXAMPLE OF CONVERTING A STATEMENT TO SOMETHING ELSE

        DO CONVERT COME FROM LABEL TO ABSTAIN FROM LABEL
        DO COME FROM (1)
(1)     DO READ OUT #1
        DO READ OUT #2
        DO GIVE UP

        PLEASE NOTE: THE COME FROM WILL RUN LIKE AN ABSTAIN FROM, SO INSTEAD
        OF AN INFINITE LOOP IT JUST CAUSES THE FIRST READ OUT TO BE SKIPPED
        AND THE PROGRAM PRODUCES JUST "II"

