#!/usr/bin/perl -w

# thin wrapper around Language::INTERCAL::Generate, to simplify
# calling from Makefile

# This file is part of CLC-INTERCAL

# Copyright (c) 2008, 2023 Claudio Calvelli, all rights reserved.

# CLC-INTERCAL is copyrighted software. However, permission to use, modify,
# and distribute it is granted provided that the conditions set out in the
# licence agreement are met. See files README and COPYING in the distribution.

use FindBin '$Bin';
use File::Spec::Functions qw(catfile);

use vars qw($VERSION $PERVERSION);
($VERSION) = ($PERVERSION = "CLC-INTERCAL/Base Generate 1.-94.-2.2") =~ /\s(\S+)$/;

$ENV{CLC_INTERCAL_ROOT} = $Bin;
$ENV{CLC_INTERCAL_BUNDLE} = '42';
require (catfile($Bin, qw(INTERCAL Generate.pm)));

Language::INTERCAL::Generate::Generate();

